// Code generated by protoc-gen-go.
// source: pb/protologpb.proto
// DO NOT EDIT!

/*
Package protologpb is a generated protocol buffer package.

It is generated from these files:
	pb/protologpb.proto

It has these top-level messages:
	Fields
	Event
	WriterOutput
	Entry
*/
package protologpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "go.pedge.io/google-protobuf"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Level is a logging level.
type Level int32

const (
	// is valid
	Level_LEVEL_NONE  Level = 0
	Level_LEVEL_DEBUG Level = 1
	Level_LEVEL_INFO  Level = 2
	Level_LEVEL_WARN  Level = 3
	Level_LEVEL_ERROR Level = 4
	Level_LEVEL_FATAL Level = 5
	Level_LEVEL_PANIC Level = 6
)

var Level_name = map[int32]string{
	0: "LEVEL_NONE",
	1: "LEVEL_DEBUG",
	2: "LEVEL_INFO",
	3: "LEVEL_WARN",
	4: "LEVEL_ERROR",
	5: "LEVEL_FATAL",
	6: "LEVEL_PANIC",
}
var Level_value = map[string]int32{
	"LEVEL_NONE":  0,
	"LEVEL_DEBUG": 1,
	"LEVEL_INFO":  2,
	"LEVEL_WARN":  3,
	"LEVEL_ERROR": 4,
	"LEVEL_FATAL": 5,
	"LEVEL_PANIC": 6,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}
func (Level) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Fields is a generic context Message used for
// the Logger functions WithField and WithFields.
type Fields struct {
	Value map[string]string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Fields) Reset()                    { *m = Fields{} }
func (m *Fields) String() string            { return proto.CompactTextString(m) }
func (*Fields) ProtoMessage()               {}
func (*Fields) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Fields) GetValue() map[string]string {
	if m != nil {
		return m.Value
	}
	return nil
}

// Event is a generic event Message used for
// the non-protobuf-specific Logger functions.
type Event struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// WriterOutput is an event Message used for
// the writer Logger functions.
type WriterOutput struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *WriterOutput) Reset()                    { *m = WriterOutput{} }
func (m *WriterOutput) String() string            { return proto.CompactTextString(m) }
func (*WriterOutput) ProtoMessage()               {}
func (*WriterOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Entry is the object serialized for logging.
type Entry struct {
	// id may not be set depending on logger options
	// it is up to the user to determine if id is required
	Id        string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Level     Level                      `protobuf:"varint,2,opt,name=level,enum=protolog.Level" json:"level,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Context   []*Entry_Message           `protobuf:"bytes,4,rep,name=context" json:"context,omitempty"`
	Event     *Entry_Message             `protobuf:"bytes,5,opt,name=event" json:"event,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Entry) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Entry) GetContext() []*Entry_Message {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Entry) GetEvent() *Entry_Message {
	if m != nil {
		return m.Event
	}
	return nil
}

// Message represents a serialized protobuf Message.
// The name is the name registered with protolog.
type Entry_Message struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Entry_Message) Reset()                    { *m = Entry_Message{} }
func (m *Entry_Message) String() string            { return proto.CompactTextString(m) }
func (*Entry_Message) ProtoMessage()               {}
func (*Entry_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func init() {
	proto.RegisterType((*Fields)(nil), "protolog.Fields")
	proto.RegisterType((*Event)(nil), "protolog.Event")
	proto.RegisterType((*WriterOutput)(nil), "protolog.WriterOutput")
	proto.RegisterType((*Entry)(nil), "protolog.Entry")
	proto.RegisterType((*Entry_Message)(nil), "protolog.Entry.Message")
	proto.RegisterEnum("protolog.Level", Level_name, Level_value)
}

var fileDescriptor0 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xdf, 0x6b, 0xa3, 0x40,
	0x10, 0xc7, 0x4f, 0x8d, 0xc9, 0x65, 0xf4, 0x12, 0xd9, 0x7b, 0x38, 0xf1, 0xb8, 0x1f, 0xf8, 0x10,
	0x42, 0xb8, 0xdb, 0x40, 0xfa, 0x52, 0xfa, 0x66, 0x5a, 0x53, 0x02, 0x56, 0x8b, 0xa4, 0x09, 0xf4,
	0xa5, 0x68, 0xb3, 0x15, 0xa9, 0x51, 0x31, 0x6b, 0x68, 0xe8, 0xbf, 0xda, 0x3f, 0xa6, 0xea, 0xd6,
	0xee, 0x4b, 0xfb, 0xb6, 0x33, 0xf3, 0xf9, 0xce, 0x77, 0x66, 0x58, 0xf8, 0x9e, 0x87, 0xd3, 0xbc,
	0xc8, 0x68, 0x96, 0x64, 0x51, 0x1e, 0xe2, 0xe6, 0x89, 0xbe, 0xb6, 0x19, 0xe3, 0x4f, 0x94, 0x65,
	0x51, 0x42, 0x18, 0x12, 0x96, 0x0f, 0x53, 0x1a, 0xef, 0xc8, 0x9e, 0x06, 0xbb, 0x9c, 0xa1, 0x66,
	0x08, 0xdd, 0x45, 0x4c, 0x92, 0xed, 0x1e, 0x4d, 0x40, 0x3e, 0x04, 0x49, 0x49, 0x74, 0xe1, 0xaf,
	0x34, 0x56, 0x66, 0x3f, 0x71, 0xdb, 0x04, 0x33, 0x00, 0xaf, 0xeb, 0xaa, 0x9d, 0xd2, 0xe2, 0x68,
	0xfc, 0x03, 0xe0, 0x11, 0x52, 0x40, 0x7a, 0x24, 0xc7, 0x4a, 0x27, 0x8c, 0xfb, 0xe8, 0x5b, 0xdb,
	0x46, 0xac, 0xc3, 0x33, 0xf1, 0x54, 0x30, 0x75, 0x90, 0xed, 0x03, 0x49, 0x29, 0x1a, 0x42, 0xaf,
	0x72, 0xdf, 0x07, 0x11, 0x61, 0xb0, 0xf9, 0x0b, 0xd4, 0x4d, 0x11, 0x53, 0x52, 0x78, 0x25, 0xcd,
	0x4b, 0xca, 0xc5, 0x75, 0x59, 0x35, 0x5f, 0x84, 0x4a, 0xd9, 0x58, 0x00, 0x88, 0xf1, 0xf6, 0xcd,
	0xe1, 0x37, 0xc8, 0x09, 0x39, 0x90, 0xa4, 0x71, 0x18, 0xcc, 0x86, 0x7c, 0x50, 0xa7, 0x4e, 0xa3,
	0xff, 0xd0, 0x7f, 0xdf, 0x52, 0x97, 0x2a, 0x46, 0x99, 0x19, 0x98, 0xdd, 0x01, 0xb7, 0x77, 0xc0,
	0xab, 0x96, 0x40, 0x63, 0xe8, 0xdd, 0x67, 0x29, 0x25, 0x4f, 0x54, 0xef, 0x34, 0x9b, 0xff, 0xe0,
	0x0d, 0x1b, 0x73, 0x7c, 0xc5, 0x66, 0x46, 0x23, 0x90, 0x49, 0xbd, 0x87, 0x2e, 0x37, 0x4d, 0x3f,
	0xe3, 0x8c, 0x11, 0xf4, 0x5a, 0x89, 0x0a, 0x9d, 0x34, 0xd8, 0x91, 0x8f, 0x6e, 0xa3, 0x4e, 0x9e,
	0x41, 0x66, 0x13, 0x0f, 0x00, 0x1c, 0x7b, 0x6d, 0x3b, 0x77, 0xae, 0xe7, 0xda, 0xda, 0x97, 0xea,
	0x4e, 0x0a, 0x8b, 0x2f, 0xec, 0xf9, 0xcd, 0xa5, 0x26, 0x70, 0x60, 0xe9, 0x2e, 0x3c, 0x4d, 0xe4,
	0xf1, 0xc6, 0xf2, 0x5d, 0x4d, 0xe2, 0x02, 0xdb, 0xf7, 0x3d, 0x5f, 0xeb, 0xf0, 0xc4, 0xc2, 0x5a,
	0x59, 0x8e, 0x26, 0xf3, 0xc4, 0xb5, 0xe5, 0x2e, 0xcf, 0xb5, 0xee, 0x5c, 0xbd, 0x05, 0xfe, 0x6f,
	0xc2, 0x6e, 0xf3, 0x3e, 0x79, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x02, 0xe9, 0x75, 0x39, 0x4f, 0x02,
	0x00, 0x00,
}
